Repository happy-sad-transcendence/backend, pull requests merged in 2025-06, with the labels that each got.

#6 feat: dto type, schema 추가 및 모노레포 구성
  .prettierignore
  .prettierrc
  apps/auth-server/.prettierignore
  apps/auth-server/Dockerfile
  apps/auth-server/package.json
  apps/auth-server/pnpm-workspace.yaml
  docker-compose.yml
  eslint.config.js
  libs/dto/package.json
  libs/dto/src/auth/AuthSetupResponse.ts
  libs/dto/src/auth/AuthVerifyRequest.ts
  libs/dto/src/auth/AuthVerifyResponse.ts
  libs/dto/src/auth/index.ts
  libs/dto/src/index.ts
  libs/dto/src/tournament/GameResponse.ts
  libs/dto/src/tournament/GameUpdateRequest.ts
  libs/dto/src/tournament/GameUpdateResponse.ts
  libs/dto/src/tournament/TournamentCreateRequest.ts
  libs/dto/src/tournament/TournamentCreateResponse.ts
  libs/dto/src/tournament/TournamentInfoResponse.ts
  libs/dto/src/tournament/TournamentListResponse.ts
  libs/dto/src/tournament/index.ts
  libs/dto/src/user/UserSettingResponse.ts
  libs/dto/src/user/UserSettingUpdateRequest.ts
  libs/dto/src/user/index.ts
  libs/dto/tsconfig.json
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: feat

#10 fix: SQLite Knex 호환성 문제 해결
  apps/main-server/migrations/.gitkeep
  apps/main-server/migrations/001.init.sql
  apps/main-server/package.json
  apps/main-server/src/plugins/external/sqlite.ts
  package.json
  pnpm-lock.yaml
Labels: fix

#12 feat: layered architecture 구조로 비즈니스 로직 작성
  apps/main-server/src/entity/base.entity.ts
  apps/main-server/src/entity/game.entity.ts
  apps/main-server/src/entity/tournament.entity.ts
  apps/main-server/src/entity/user.entity.ts
  apps/main-server/src/repository/game.repository.ts
  apps/main-server/src/repository/tournament.repository.ts
  apps/main-server/src/repository/user.repository.ts
  apps/main-server/src/routes/api/tournament.controller.ts
  apps/main-server/src/routes/api/user.controller.ts
  apps/main-server/src/service/game.service.ts
  apps/main-server/src/service/tournament.service.ts
  apps/main-server/src/service/user.service.ts
Labels: feat

#15 chore: Auth 서버 swagger 구성 및 api 경로 재설정
  apps/auth-server/package.json
  apps/auth-server/src/app.ts
  apps/auth-server/src/plugins/swagger.ts
  apps/auth-server/src/route/auth.ts
  apps/auth-server/src/route/index.ts
  apps/auth-server/src/route/oauth.ts
  apps/auth-server/src/route/twoFactor.ts
  apps/auth-server/src/routes/api/auth/oauth.ts
  apps/auth-server/src/routes/api/auth/twoFactor.ts
  apps/auth-server/src/server.ts
  libs/dto/src/error/ErrorResponse.ts
  libs/dto/src/error/index.ts
  libs/dto/src/index.ts
  package.json
  pnpm-lock.yaml
Labels: chore

#19 feat: jwt 쿠키 추가 및 유저 데이터 생성, 조회를 위한 메인 서버 요청 서비스 구현
  apps/auth-server/package.json
  apps/auth-server/src/plugins/jwt.ts
  apps/auth-server/src/plugins/vault.ts
  apps/auth-server/src/routes/api/auth/oauth.ts
  apps/auth-server/src/routes/api/auth/twoFactor.ts
  apps/auth-server/src/routes/api/autohooks.ts
  apps/auth-server/src/service/vault.ts
  apps/auth-server/src/services/auth.service.ts
  apps/auth-server/src/services/oauth.service.ts
  apps/auth-server/src/services/twoFactor.service.ts
  libs/dto/src/index.ts
  libs/dto/src/token/GooglePayload.ts
  libs/dto/src/token/TwoFactorPayload.ts
  libs/dto/src/token/UserPayload.ts
  libs/dto/src/token/VaultPayload.ts
  libs/dto/src/token/index.ts
  pnpm-lock.yaml
Labels: feat
